### ISSUE TITLE
Badly parsed missionRewards node(s)

### ISSUE THREAD

**Issue by Xuerian** [WFCD/warframe-drop-data#1]
Cholistan/Europa, at least

Drops aren't broken into rotations.

**Comment by atomicptr** [comment]
It looks like there is generally something wrong with that (and possibly other) node(s).

![image](https://user-images.githubusercontent.com/674705/29859317-d21bc164-8d61-11e7-8ef0-fe41afab5df6.png)

vs

https://github.com/WFCD/warframe-drop-data/blob/gh-pages/data/missionRewards/Europa/Cholistan.json

**Comment by Xuerian** [comment]
Time to take the html behind the shed and give it the old slice-n-dice myself.

I really don't understand DE's reluctance to provide data files.

**Comment by atomicptr** [comment]
> I really don't understand DE's reluctance to provide data files.

Who does :)

**Comment by atomicptr** [comment]
Got an interesting lead from @aliasfalse with "looks like the parser for the drop tables is combining mission rewards for eris, oestrus and eris, phalan" this is probably the issue, when I find some time, I'll try to fix it.

**Comment by Xuerian** [comment]
No rush on my part, I wrote a very simple one internally that seems to work fine.

**Comment by TobiTenno** [comment]
I think somebody got it working, so i'm prolly gonna close this...

**Comment by atomicptr** [comment]
At least the Cholistan node looks good :).

**Comment by TobiTenno** [comment]
lol, that's good
