### ISSUE TITLE
Diff page still compares things that shouldn't be compared

### ISSUE THREAD

**Issue by atomicptr** [WFCD/warframe-drop-data#18]
Just seen this: 

![image](https://user-images.githubusercontent.com/674705/40468242-1aca13be-5f2d-11e8-8b16-6baea928647d.png)

that shouldn't happen, have to figure out how to change that ho :>. Obviously the node didn't get renamed and all drops changed but instead it compared two completely different nodes with each other.

**Comment by TobiTenno** [comment]
It's probably because they're never really sorted in a particular order....

**Comment by Senexis** [comment]
The referenced PR adds an "_id" field and fixes the issue.

**Comment by TobiTenno** [comment]
right, @atomicptr doing both.... give an id, sort by ID

**Comment by Senexis** [comment]
There's no need to sort the array as long as it has IDs. Sorting it doesn't add anything because all the transients already have a unique ID at that point and is good enough.

**Comment by Senexis** [comment]
It's not. It comparing to text is only being done in the case when the ID is missing, so adding an ID to the transients is _really_ good enough.

**Comment by atomicptr** [comment]
@Senexis your diff page actually shows the one thing that bothers me about this, instead of seeing hey shit changed for this thing you just see "THIS GOT REMOVED", "THIS GOT ADDED". :D

**Comment by Senexis** [comment]
Yep, which is why the PR exists, to attempt to fix it. :-)

The only reason this is happening is because the transients never had an "_id" field.

**Comment by atomicptr** [comment]
Fixed with #17
