### ISSUE TITLE
Drop website displays wrong drop chance

### ISSUE THREAD

**Issue by atomicptr** [WFCD/warframe-drop-data#24]
The website displays the wrong drop chance for "Intact Sentient Core" as you can see here:

![image](https://user-images.githubusercontent.com/674705/41593460-65363f70-73c0-11e8-9d90-23a60cdbf309.png)

It says "12.xx%" but inside of the all.json file it says "4x%":

![image](https://user-images.githubusercontent.com/674705/41593443-59d660c4-73c0-11e8-9d47-6d9af41c4851.png)

This might affect more items.

**Comment by TobiTenno** [comment]
Oddly, I'm wondering if something is messing up when it's filtering the items? but that's very odd...

**Comment by atomicptr** [comment]
Probably, haven't found the time to look into it yet tho.

**Comment by Senexis** [comment]
The site takes into account the chance to drop an item, which then draws from the items the enemy can drop.

So, if an enemy has a 50% chance to drop an item and has two items (let's make it easy and say that; item 1: 50%, item 2: 50%) to choose between, the actual drop rate will be lower than the number pre-calculation.

So: when item 1 drops from the enemy, the actual chance will be 50% (chance of item 1) of 50% (chance to drop an item at all) meaning 25% chance to drop the item when the enemy is killed.

The only issue I notice now is that the text doesn't get updated based on this calculated result, I don't think 12% is common.

Should you want this to be changed, feel free to edit the formatData function to take the calculations out of the "chance" properties, though that won't make the chances accurate as it doesn't account for the possibility that a killed enemy doesn't drop an item.

**Comment by atomicptr** [comment]
Yup, you're right it's actually correct.

**Comment by TobiTenno** [comment]
yeah, it's definitely still odd. we should probably add a "disclaimer" somewhere
