### ISSUE TITLE
Search from drop location not working?

### ISSUE THREAD

**Issue by Nariety** [WFCD/warframe-drop-data#26]
### Warframe Drops Site Issue
---

**Summary (short):**
For example, searching for "assassination" "general sargas ruk" "mars" didn't show results for me. I noticed the functionality was added on April 21st according to issue #5 so something might have messed it up from then?

---
**If issue, Reproduction:**
Search for location keywords in the search box.

---
**Mockups, screenshots, evidence:**
assassination:
![assassination](https://user-images.githubusercontent.com/28118225/41884988-90237172-7928-11e8-8bda-5102d932a6e5.png)
general sargas ruk
![generalsargasruk](https://user-images.githubusercontent.com/28118225/41884994-9328bc9c-7928-11e8-858b-bc6b2b73136a.png)
mars
![mars](https://user-images.githubusercontent.com/28118225/41884997-961d93e6-7928-11e8-8c51-4365d74d3e3b.png)

---

**Comment by atomicptr** [comment]
It works fine for me, you forgot to change the location filter :). Maybe it should be Locations and Items by default?

![image](https://user-images.githubusercontent.com/674705/41897284-2f080264-7927-11e8-8450-ed9a5ca9cdcc.png)

**Comment by TobiTenno** [comment]
As above, this looks to be an accident rather than site error, I'll go ahead and close.

**Comment by Nariety** [comment]
oops... Sorry about that. But it might be a good idea to enable them both by default.
