### ISSUE TITLE
relic locations

### ISSUE THREAD

**Issue by nonchip** [WFCD/warframe-drop-data#42]
### Warframe Drops Site Feature Request
---

**Summary (short):**

essentially the same as modLocations just for relics.

---

dunno what else to write about it, seems pretty clear :P

**Comment by TobiTenno** [comment]
relics are part of normal location droptables already
mods drop from enemies, not rotation/location rewards

**Comment by nonchip** [comment]
yes, yes, and yes. and?

**Comment by atomicptr** [comment]
@nonchip is your issue that you miss the new data endpoints? Like X by avatar / X by drop, which we discussed in #44.

**Comment by nonchip** [comment]
@atomicptr no rather the fact we have some endpoints that combine data in a useful way (like modLocations) but for other stuff we don't (like what I called "relicLocations" being a table of where to get relics) so we have to parse and reconstruct that info (from iterating the mission drops and filtering the result for example) so i was wondering whether we could get endpoints like modLocations for other types loot.

i mean doing the logic to them client side isn't that hard (see https://gitlab.com/nonchip/moonbook/snippets/1792199) but we do have that "quality of life info" for some items and not for others, so why not add it?

**Comment by TobiTenno** [comment]
the ones we already have are combined by location already, relics aren't, simple as that
