### ISSUE TITLE
Should we change the format?

### ISSUE THREAD

**Issue by atomicptr** [WFCD/warframe-drop-data#44]
DE changed their structure recently which changed certain keys, for instance modLocations is now modByDrop and enemyModTable is modByAvatar. They also removed misc items and replaced it with resources as described in #43.

Question is, should we keep the data as is (using old terminology) or change it, which would probably break everything that is connected to this data set.

@TobiTenno

**Comment by TobiTenno** [comment]
Let's keep our format the same, cause i don't know if it's really necessary to rename it to things less intelligible. Keep them in the same objects we've been using.

**Comment by atomicptr** [comment]
Question is if it makes sense to maybe duplicate the data? Or create a new endpoint that isn't all.json / all.slim.json :thinking:

**Comment by TobiTenno** [comment]
in this case it's providing consistency while also providing passivity by not just dropping the endpoint
