### ISSUE TITLE
incomplete information (parsing error)

### ISSUE THREAD

**Issue by agalera** [WFCD/warframe-drop-data#45]
### Warframe Drops Site Issue
---

**Summary (short):**
Bullet Dance only appears once, but it really drop in 3 different places:

Void/Stribog (Caches), Rotation C	Rare	3.67%
Void/Marduk (Caches), Rotation C	Rare	4.42%
Plains of Eidolon Incursions, Rotation B	Rare	1.01%

It seems that when you add the data to the array in missionRewards, it is used as the "Void/Marduk" key, but there are two types, cache and sabotage, and only one is stored, the same thing happens with Stribog.

I do not know if this happens in other cases
---
**If issue, Reproduction:**
1. check json

**Comment by oohshiny** [comment]
I'd add to this that all of the Void mission rewards (e.g. caches) are broken since relics were added to all Void locations. See for example "Xiphos Avionics" which should drop from Marduk caches (according to the published drop tables), but doesn't show as doing so according to the parsed data.

**Comment by oohshiny** [comment]
As of approx. Dec 2018 when relics were added to all Void drop tables, the two Void Sabotage nodes (Stribog and Marduk) now have 2 drop tables in the official drop table and are skipped while being parsed. A possible fix is as follows:

`diff --git a/lib/missionRewards.js b/lib/missionRewards.js
index 56236a1..894159a 100644
--- a/lib/missionRewards.js
+++ b/lib/missionRewards.js
@@ -24,6 +24,10 @@ module.exports = function($) {
                     missionRewards[location.planet] = {}
                 }
 
+                if(missionRewards[location.planet][location.location] && location.planet == "Void") {
+                    location.location += " (Extra)"
+                }
+
                 if (!missionRewards[location.planet][location.location]) {
                     missionRewards[location.planet][location.location] = {
                         gameMode: location.gameMode,
`

**Comment by TobiTenno** [comment]
closing with #56
