### ISSUE TITLE
Move build process to Travis

### ISSUE THREAD

**Issue by atomicptr** [WFCD/warframe-drop-data#52]
Right now the script is running once per hour on my private server, but I think this should run on a Travis CI cron job instead, mostly because it's easier to determine why and when builds fail (Also the script can then be run on command, which would be useful when a new patch drops).

We'd probably have to move the entire page to a new branch and make it build into gh-pages.

**Comment by TobiTenno** [comment]
Sounds good to me.

**Comment by TobiTenno** [comment]
do you need help to do it, or do you have a script ready for it?

**Comment by atomicptr** [comment]
I haven't even started on this beyond a few ideas, lack of time generally is my issue rn :). So feel free to do it if you want to!
