### ISSUE TITLE
Neo Z4 Relic contains drop data for all Requiem Relics

### ISSUE THREAD

**Issue by DrunkenSquirrel** [WFCD/warframe-drop-data#58]
### Warframe Drops Site Issue
---

Drop data for the Neo Z4 Relic contains all the drops for the new Requiem Relics introduced with the Old Blood update.

---
**If issue, Reproduction:**
n/a

---
**Mockups, screenshots, evidence:**

Search for Kuva on the site, or look in the raw drop data for Neo Z4.

---

**Additional context**
n/a

**Comment by TobiTenno** [comment]
yeah, looks like they probably added another table or a structure we weren't ready for, since they're a new "tier"
