### ISSUE TITLE
Add bounty rewards for Deimos/Necralisk

### ISSUE THREAD

**Issue by Lyrex** [WFCD/warframe-drop-data#64]
The drop table seems to now include the current bounties. I could implement the logic for the parsing (it's the same like the ones for cetus and fortuna) but I'm not sure what the naming convention of the current modules is.

![Deimos Bounty Rewards](https://i.lxn.re/i/LAtUFvqx.png)

**Comment by TobiTenno** [comment]
ah, the naming convention is the id of the section in the html. feel free to give it a shot, or i'm sure one of us will try soon
