### ISSUE TITLE
Add additional search methods: exact, regex

### ISSUE THREAD

**Issue by huang-jy** [WFCD/warframe-drop-data#66]
### Warframe Drops Site Feature Request
---

**Summary (short):**
Provide the option to search by exact string

Provide the option to search using regex

---
**Detailed requirements of the feature**

_As a user, I should be able to indicate that I wish to search for a drop using an exact search string._
_As a user, those search results should match the search string **entirely**._

_As a user, I should be able to search for a drop using a regex._
_As a user, those search results should match the regex._

---
**Mockups:**

Paint, photoshop mockups, sketchup, whatever you're envisioning.

A tickbox to indicate whether or not "Exact match" is desired
If this tickbox is selected, then searching for "Bite" should match "Bite" *only*, and not Frostbite. Searching for "Rush" should match "Rush" only, and not "Blood Rush", or "Gladiator Rush"

A tickbox to indicate whether or not "regex match" is desired
If this tickbox is selected, then searching for "`^bite$`" should match "Bite" *only*, and not Frostbite. Similarly, searching for "`^(gladiator )?rush$`" would match "Rush", "Gladiator Rush" but not "Blood Rush"

---

**Additional context**
Add any other context about the request here.

**Comment by TobiTenno** [comment]
i'll give my hand at this for the search side first to see if it even works manually through the url, but no promises
