### ISSUE TITLE
enemyModTables.json enemyModDropChance

### ISSUE THREAD

**Issue by larvanitis** [WFCD/warframe-drop-data#68]
### Warframe Drops JSON Data Issue
---

**Summary (short):**
The property `enemyModDropChance` is formatted as string.
Shouldn't it be a number like all other `chance` properties?

---
**Mockups, screenshots, evidence:**

Look in https://github.com/WFCD/warframe-drop-data/blob/main/data/enemyModTables.json

**Comment by TobiTenno** [comment]
We're not changing data format for passivity purposes.
