### ISSUE TITLE
enemyModTables.json ememyModDropChance (property dup)

### ISSUE THREAD

**Issue by larvanitis** [WFCD/warframe-drop-data#69]
### Warframe Drops JSON Data Issue
---

**Summary (short):**
There is a duplicate (and mispelled) property `ememyModDropChance` (_e**m**emy_ vs _enemy_).

---
**Mockups, screenshots, evidence:**

Look in https://github.com/WFCD/warframe-drop-data/blob/main/data/enemyModTables.json

**Comment by TobiTenno** [comment]
It's been discussed before, but we've chosen not to remove it for passivity with anyone using the old spelling. We corrected the spelling, as you can see, some time ago.
