### ISSUE TITLE
enemyBlueprintTables.json wrong property `mods`

### ISSUE THREAD

**Issue by larvanitis** [WFCD/warframe-drop-data#70]
### Warframe Drops JSON Data Issue
---

**Summary (short):**
Each entry in this file contains a `mods[]` property, which looks like a copy-paste left over.
Only `items[]` should be here.

---
**Mockups, screenshots, evidence:**

Look in https://github.com/WFCD/warframe-drop-data/blob/main/data/enemyBlueprintTables.json

**Comment by TobiTenno** [comment]
1) linking to a json file really doesn't help
2) these are all parsed out each time. If it's an old file, it sticks around for passivity.
