### ISSUE TITLE
enemyBlueprintTables.json sketchy *DropChance properties

### ISSUE THREAD

**Issue by larvanitis** [WFCD/warframe-drop-data#71]
### Warframe Drops JSON Data Issue
---

**Summary (short):**
Each entry has these two properties `blueprintDropChance` & `enemyDropChance`, which (always?) have the same value. Only one of these is required.

Also, the value type and format looks wrong. It is like `"nce: 15.00"`, while it should be a number like `15`.

---
**Mockups, screenshots, evidence:**

Look in https://github.com/WFCD/warframe-drop-data/blob/main/data/enemyBlueprintTables.json

**Comment by TobiTenno** [comment]
It's a sting for the purposes of maintaining precision, and has been since we started, so we probably won't be dropping those off.
