### ISSUE TITLE
Request all drop locations for a specific item (API)

### ISSUE THREAD

**Issue by Elfahor** [WFCD/warframe-drop-data#74]
### Warframe Drops API Feature Request
---

**Summary (short):**
Be able to get data about drop location for a specific item

---
**Detailed requirements of the feature**

_As a user, I'd should be able to search for a location._
I should be able to request data/locations/{itemName}.json to find all the enemies/missions/events this item/mod/blueprint drops on.

---
**Mockups:**

It should look like that:
![mockup](https://user-images.githubusercontent.com/57094476/119163907-2676a780-ba5c-11eb-9a95-60557c69c584.png)

---

**Additional context**
I was making a little .NET wrapper for this data, and it would be much easier for me if I could just lookup like that.

**Comment by TobiTenno** [comment]
you already can search for a specific location, which is what your detailed description looks like

You're not going to be able search for a specific item across all places, as this is a set of data files, not an api.

If you'd like to leverage the api, you can use the api that is described in https://docs.warframestat.us

Here's an example for forma: https://api.warframestat.us/drops/search/forma

**Comment by Elfahor** [comment]
Thanks for the quick reply. I will use what you described.
