### ISSUE TITLE
Question: How to know which items are vaulted?

### ISSUE THREAD

**Issue by kylhuk** [WFCD/warframe-drop-data#75]
Hey there,

thanks for the great work you put in this project. This makes life a lot easier for a lot of data analysts :)

I was looking at your API's and data files and somehow was not able to find out if you distinguish between an item which is vaulted or not. E.g. the Axi S4 relict is vaulted right now, but I can't seem to find the information in your data.

What am I missing?

**Comment by TobiTenno** [comment]
It's not really the point of drop data. we have some of said information over in https://github.com/WFCD/warframe-items

**Comment by kylhuk** [comment]
Nevermind, it is actually part of the drop data, just not the way I expected it. The absence of an entry in the drop data means, it is currently vaulted. So right now you can't find any Axi S4 in your data.

Thanks for your help, though.

Case closed :)

**Comment by TobiTenno** [comment]
sure, if you wanna go about it that way.
