### ISSUE TITLE
Common relic drops are marked as Uncommon

### ISSUE THREAD

**Issue by Mustachipleb** [WFCD/warframe-drop-data#86]
### Warframe Drops Site Issue
---

**Summary (short):**
As far as I can see, no relic drop data has Common drops defined. Common drops and their chances are always the Uncommon value.

---
**If issue, Reproduction:**
1. Go to any Relic JSON
2. Check rewards rarity and chance

**Comment by TobiTenno** [comment]
this is probably due to the chances themselves being adjusted based on the chance of a drop actually occurring. we use these combined/simplified chances that combine `chance_of_a_drop * chance_of_this_drop` for the computed final that we display here

**Comment by TobiTenno** [comment]
Further, you can see [here](https://github.com/WFCD/warframe-drop-data/blob/862f6deb2fc1998a061ec2e7884d0fa1d3db6a6a/lib/relics.js#L34), we just use the rarity from warframe.com/droptables that we parse out

**Comment by TobiTenno** [comment]
sorry, just realized i should've just shown you the official tables... 
![image](https://github.com/user-attachments/assets/a61db0f3-809b-4812-8ac5-413a79babde7)


failing the smell test, unfortunately doesn't mean it's wrong, just that DE has stinky tables

**Comment by Mustachipleb** [comment]
I think I understand what's going on, the rarity text on DE's side is determined by some set percentage thresholds, and doesn't actually reflect the rarity as it is presented in-game. So, not necessarily stinky tables, but a tad confusing presentation of the data :D

**Comment by TobiTenno** [comment]
for sure!
